---
- name: DEPLOY AS3 Playbook
  hosts: localhost
  connection: local
  gather_facts: no

  vars:

  vars_files:
  - ../creds/bigip_creds.yaml

  tasks:
  - name: Deploy AS3 Playbook
    uri:
      url: https://20.0.58.197:8443/mgmt/shared/appsvcs/declare
      user: "{{ bigip_username }}"
      password: "{{ bigip_password }}"
      validate_certs: false
      method: POST
      body: "{{ lookup('file','as3.json') }}"
      force_basic_auth: yes
      status_code: 200
      body_format: json


...